//! Input fingerprinting for incremental plan generation.
//!
//! Computes a SHA256 hash of everything that affects the build plan output:
//! unit2nix version, CLI flags, Cargo.lock, all Cargo.toml files in the
//! workspace, and git HEADs of out-of-tree path dependencies. When the
//! fingerprint matches the stored value in an existing build plan,
//! regeneration is skipped.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result};
use sha2::{Digest, Sha256};

use crate::cli::Cli;

/// Directories to skip when walking for Cargo.toml files.
const SKIP_DIRS: &[&str] = &["target", ".git", "node_modules"];

/// Compute a SHA256 fingerprint of all inputs that affect the build plan.
///
/// The fingerprint covers:
/// - unit2nix version (format changes require regeneration)
/// - CLI flags that affect dependency resolution
/// - Cargo.lock content (exact dependency versions)
/// - All Cargo.toml files under the workspace root (features, deps, targets)
/// - Git HEAD of every out-of-tree path dependency's repo
///
/// The fingerprint is deterministic: same inputs always produce the same hash.
///
/// # Errors
///
/// Returns an error if Cargo.lock cannot be read.
#[must_use = "compare this hash against the stored inputs_hash to decide whether to skip"]
pub fn compute_inputs_hash(cli: &Cli) -> Result<String> {
    let mut hasher = Sha256::new();

    // unit2nix version — format changes require regeneration
    hasher.update(b"version:");
    hasher.update(env!("CARGO_PKG_VERSION").as_bytes());
    hasher.update(b"\n");

    // CLI flags that affect resolution
    hasher.update(b"cli:");
    hasher.update(
        format!(
            "features={:?}\nall_features={}\nno_default_features={}\n\
             target={:?}\npackage={:?}\nbin={:?}\ninclude_dev={}\nmembers={:?}\n\
             workspace={}\nbuild_std={:?}\nbuild_std_features={:?}\n",
            cli.features,
            cli.all_features,
            cli.no_default_features,
            cli.target,
            cli.package,
            cli.bin,
            cli.include_dev,
            cli.members,
            cli.workspace,
            cli.build_std,
            cli.build_std_features,
        )
        .as_bytes(),
    );

    // Cargo.lock content
    let workspace_dir = cli.manifest_path.parent().unwrap_or(Path::new("."));
    let lock_path = workspace_dir.join("Cargo.lock");
    let lock_content = std::fs::read(&lock_path).with_context(|| {
        format!(
            "failed to read {}. Run `cargo generate-lockfile` first",
            lock_path.display()
        )
    })?;
    hasher.update(b"cargo-lock:");
    hasher.update(&lock_content);

    // All Cargo.toml files under the workspace root (sorted for determinism)
    let mut toml_paths = Vec::new();
    collect_cargo_tomls(workspace_dir, &mut toml_paths);
    toml_paths.sort();

    for path in &toml_paths {
        if let Ok(content) = std::fs::read(path) {
            let rel = path.strip_prefix(workspace_dir).unwrap_or(path);
            hasher.update(b"cargo-toml:");
            hasher.update(rel.to_string_lossy().as_bytes());
            hasher.update(b":");
            hasher.update(&content);
        }
    }

    // Git HEAD of out-of-tree path dependencies.
    //
    // When a Cargo.toml has `path = "../sibling-repo/crates/foo"`, changes in
    // that repo don't touch Cargo.lock or any workspace file. Without this,
    // the fingerprint stays stale and `unit2nix` skips regeneration even though
    // the resolved git rev would change.
    let external_heads = collect_out_of_tree_git_heads(&toml_paths, workspace_dir);
    for (repo_root, head) in &external_heads {
        hasher.update(b"ext-git-head:");
        hasher.update(repo_root.as_bytes());
        hasher.update(b":");
        hasher.update(head.as_bytes());
        hasher.update(b"\n");
    }

    Ok(format!("{:x}", hasher.finalize()))
}

/// Read the `inputsHash` from an existing build plan file.
///
/// Returns `None` if the file doesn't exist, can't be parsed, or has
/// no `inputsHash` field (e.g., plans generated by older unit2nix versions).
#[must_use]
pub fn read_existing_inputs_hash(path: &Path) -> Option<String> {
    let content = std::fs::read_to_string(path).ok()?;
    let value: serde_json::Value = serde_json::from_str(&content).ok()?;
    value.get("inputsHash")?.as_str().map(String::from)
}

/// Recursively collect all Cargo.toml files under a directory.
///
/// Skips `target/`, `.git/`, and `node_modules/` to avoid noise from
/// build artifacts, vendored dependencies, and non-Rust tooling.
fn collect_cargo_tomls(dir: &Path, out: &mut Vec<PathBuf>) {
    let cargo_toml = dir.join("Cargo.toml");
    if cargo_toml.is_file() {
        out.push(cargo_toml);
    }

    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };

    for entry in entries.flatten() {
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if !file_type.is_dir() {
            continue;
        }
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if SKIP_DIRS.iter().any(|s| *s == &*name_str) {
            continue;
        }
        collect_cargo_tomls(&entry.path(), out);
    }
}

/// Extract path dependency values from a Cargo.toml's dependency tables.
///
/// Parses the TOML and collects every `path = "..."` value from
/// `[dependencies]`, `[dev-dependencies]`, and `[build-dependencies]`.
fn extract_path_deps(toml_content: &str) -> Vec<String> {
    let Ok(doc) = toml_content.parse::<toml::Table>() else {
        return Vec::new();
    };

    let dep_tables = [
        "dependencies",
        "dev-dependencies",
        "build-dependencies",
    ];

    let mut paths = Vec::new();
    for table_name in &dep_tables {
        if let Some(toml::Value::Table(deps)) = doc.get(*table_name) {
            for (_name, spec) in deps {
                if let Some(path) = spec.get("path").and_then(|v| v.as_str()) {
                    paths.push(path.to_string());
                }
            }
        }
    }
    paths
}

/// For each out-of-tree path dependency, resolve its git repo root and HEAD.
///
/// Returns a sorted, deduplicated list of `(repo_root, HEAD_rev)` pairs.
/// Repos that aren't git-controlled or have no commits are silently skipped.
fn collect_out_of_tree_git_heads(
    toml_paths: &[PathBuf],
    workspace_dir: &Path,
) -> Vec<(String, String)> {
    let ws_canon = workspace_dir.canonicalize().unwrap_or_else(|_| workspace_dir.to_path_buf());

    // Deduplicate by canonical repo root so we only call git once per repo.
    let mut seen_repos: BTreeSet<String> = BTreeSet::new();
    let mut result: Vec<(String, String)> = Vec::new();

    for toml_path in toml_paths {
        let manifest_dir = toml_path.parent().unwrap_or(Path::new("."));
        let content = match std::fs::read_to_string(toml_path) {
            Ok(c) => c,
            Err(_) => continue,
        };

        for rel_path in extract_path_deps(&content) {
            let dep_dir = manifest_dir.join(&rel_path);
            let dep_canon = match dep_dir.canonicalize() {
                Ok(p) => p,
                Err(_) => continue, // path doesn't exist on disk
            };

            // Skip if it's inside the workspace — already covered by Cargo.toml hashing.
            if dep_canon.starts_with(&ws_canon) {
                continue;
            }

            // Find the git repo root for this path.
            let repo_root = match git_repo_root(&dep_canon) {
                Some(r) => r,
                None => continue, // not in a git repo
            };

            if seen_repos.contains(&repo_root) {
                continue;
            }
            seen_repos.insert(repo_root.clone());

            if let Some(head) = git_head(&repo_root) {
                result.push((repo_root, head));
            }
        }
    }

    result
}

/// Get the git repository root directory for a path.
fn git_repo_root(dir: &Path) -> Option<String> {
    Command::new("git")
        .args(["-C", &dir.to_string_lossy(), "rev-parse", "--show-toplevel"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
}

/// Get the HEAD commit of a git repository.
fn git_head(repo_root: &str) -> Option<String> {
    Command::new("git")
        .args(["-C", repo_root, "rev-parse", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn make_cli() -> Cli {
        Cli {
            manifest_path: PathBuf::from("./Cargo.toml"),
            features: None,
            bin: None,
            package: None,
            all_features: false,
            no_default_features: false,
            target: None,
            output: PathBuf::from("build-plan.json"),
            stdout: false,
            check_overrides: false,
            include_dev: false,
            members: None,
            no_check: false,
            json: false,
            force: false,
            workspace: false,
            no_locked: false,
            build_std: None,
            build_std_features: None,
        }
    }

    #[test]
    fn fingerprint_is_deterministic() {
        let cli = make_cli();
        let h1 = compute_inputs_hash(&cli).unwrap();
        let h2 = compute_inputs_hash(&cli).unwrap();
        assert_eq!(h1, h2);
    }

    #[test]
    fn fingerprint_is_sha256_hex() {
        let cli = make_cli();
        let hash = compute_inputs_hash(&cli).unwrap();
        assert_eq!(hash.len(), 64);
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn fingerprint_changes_with_features() {
        let cli1 = make_cli();
        let mut cli2 = make_cli();
        cli2.features = Some("serde".to_string());

        let h1 = compute_inputs_hash(&cli1).unwrap();
        let h2 = compute_inputs_hash(&cli2).unwrap();
        assert_ne!(h1, h2, "different features should produce different hashes");
    }

    #[test]
    fn fingerprint_changes_with_target() {
        let cli1 = make_cli();
        let mut cli2 = make_cli();
        cli2.target = Some("aarch64-unknown-linux-gnu".to_string());

        let h1 = compute_inputs_hash(&cli1).unwrap();
        let h2 = compute_inputs_hash(&cli2).unwrap();
        assert_ne!(h1, h2, "different targets should produce different hashes");
    }

    #[test]
    fn fingerprint_changes_with_include_dev() {
        let cli1 = make_cli();
        let mut cli2 = make_cli();
        cli2.include_dev = true;

        let h1 = compute_inputs_hash(&cli1).unwrap();
        let h2 = compute_inputs_hash(&cli2).unwrap();
        assert_ne!(h1, h2, "include_dev should change the hash");
    }

    #[test]
    fn fingerprint_changes_with_workspace() {
        let cli1 = make_cli();
        let mut cli2 = make_cli();
        cli2.workspace = true;

        let h1 = compute_inputs_hash(&cli1).unwrap();
        let h2 = compute_inputs_hash(&cli2).unwrap();
        assert_ne!(h1, h2, "workspace should change the hash");
    }

    #[test]
    fn read_existing_hash_missing_file() {
        assert_eq!(read_existing_inputs_hash(Path::new("/nonexistent")), None);
    }

    #[test]
    fn read_existing_hash_no_field() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("plan.json");
        std::fs::write(&path, r#"{"version": 1, "crates": {}}"#).unwrap();
        assert_eq!(read_existing_inputs_hash(&path), None);
    }

    #[test]
    fn read_existing_hash_present() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("plan.json");
        std::fs::write(
            &path,
            r#"{"version": 1, "inputsHash": "abc123def456"}"#,
        )
        .unwrap();
        assert_eq!(
            read_existing_inputs_hash(&path),
            Some("abc123def456".to_string())
        );
    }

    #[test]
    fn collect_cargo_tomls_finds_root() {
        let mut paths = Vec::new();
        collect_cargo_tomls(Path::new("."), &mut paths);
        assert!(
            paths.iter().any(|p| p.ends_with("Cargo.toml")),
            "should find at least the root Cargo.toml"
        );
    }

    #[test]
    fn collect_cargo_tomls_skips_target() {
        let mut paths = Vec::new();
        collect_cargo_tomls(Path::new("."), &mut paths);
        assert!(
            !paths.iter().any(|p| p
                .components()
                .any(|c| c.as_os_str() == "target")),
            "should not descend into target/"
        );
    }

    #[test]
    fn extract_path_deps_finds_deps() {
        let toml = r#"
[package]
name = "test"
version = "0.1.0"

[dependencies]
foo = { path = "../foo" }
bar = "1.0"
baz = { version = "2", features = ["serde"] }
qux = { path = "crates/qux" }

[dev-dependencies]
testlib = { path = "../testlib" }

[build-dependencies]
codegen = { path = "../codegen", version = "0.1" }
"#;
        let mut paths = extract_path_deps(toml);
        paths.sort();
        assert_eq!(paths, vec![
            "../codegen",
            "../foo",
            "../testlib",
            "crates/qux",
        ]);
    }

    #[test]
    fn extract_path_deps_empty_manifest() {
        let toml = r#"
[package]
name = "test"
version = "0.1.0"
"#;
        assert!(extract_path_deps(toml).is_empty());
    }

    #[test]
    fn extract_path_deps_no_path_deps() {
        let toml = r#"
[package]
name = "test"
version = "0.1.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
tokio = "1"
"#;
        assert!(extract_path_deps(toml).is_empty());
    }

    #[test]
    fn extract_path_deps_invalid_toml() {
        assert!(extract_path_deps("not valid toml {{{").is_empty());
    }
}
