//! Input fingerprinting for incremental plan generation.
//!
//! Computes a SHA256 hash of everything that affects the build plan output:
//! unit2nix version, CLI flags, Cargo.lock, and all Cargo.toml files in the
//! workspace. When the fingerprint matches the stored value in an existing
//! build plan, regeneration is skipped.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use sha2::{Digest, Sha256};

use crate::cli::Cli;

/// Directories to skip when walking for Cargo.toml files.
const SKIP_DIRS: &[&str] = &["target", ".git", "node_modules"];

/// Compute a SHA256 fingerprint of all inputs that affect the build plan.
///
/// The fingerprint covers:
/// - unit2nix version (format changes require regeneration)
/// - CLI flags that affect dependency resolution
/// - Cargo.lock content (exact dependency versions)
/// - All Cargo.toml files under the workspace root (features, deps, targets)
///
/// The fingerprint is deterministic: same inputs always produce the same hash.
///
/// # Errors
///
/// Returns an error if Cargo.lock cannot be read.
#[must_use = "compare this hash against the stored inputs_hash to decide whether to skip"]
pub fn compute_inputs_hash(cli: &Cli) -> Result<String> {
    let mut hasher = Sha256::new();

    // unit2nix version — format changes require regeneration
    hasher.update(b"version:");
    hasher.update(env!("CARGO_PKG_VERSION").as_bytes());
    hasher.update(b"\n");

    // CLI flags that affect resolution
    hasher.update(b"cli:");
    hasher.update(
        format!(
            "features={:?}\nall_features={}\nno_default_features={}\n\
             target={:?}\npackage={:?}\nbin={:?}\ninclude_dev={}\nmembers={:?}\n\
             workspace={}\nbuild_std={:?}\nbuild_std_features={:?}\n",
            cli.features,
            cli.all_features,
            cli.no_default_features,
            cli.target,
            cli.package,
            cli.bin,
            cli.include_dev,
            cli.members,
            cli.workspace,
            cli.build_std,
            cli.build_std_features,
        )
        .as_bytes(),
    );

    // Cargo.lock content
    let workspace_dir = cli.manifest_path.parent().unwrap_or(Path::new("."));
    let lock_path = workspace_dir.join("Cargo.lock");
    let lock_content = std::fs::read(&lock_path).with_context(|| {
        format!(
            "failed to read {}. Run `cargo generate-lockfile` first",
            lock_path.display()
        )
    })?;
    hasher.update(b"cargo-lock:");
    hasher.update(&lock_content);

    // All Cargo.toml files under the workspace root (sorted for determinism)
    let mut toml_paths = Vec::new();
    collect_cargo_tomls(workspace_dir, &mut toml_paths);
    toml_paths.sort();

    for path in &toml_paths {
        if let Ok(content) = std::fs::read(path) {
            let rel = path.strip_prefix(workspace_dir).unwrap_or(path);
            hasher.update(b"cargo-toml:");
            hasher.update(rel.to_string_lossy().as_bytes());
            hasher.update(b":");
            hasher.update(&content);
        }
    }

    Ok(format!("{:x}", hasher.finalize()))
}

/// Read the `inputsHash` from an existing build plan file.
///
/// Returns `None` if the file doesn't exist, can't be parsed, or has
/// no `inputsHash` field (e.g., plans generated by older unit2nix versions).
#[must_use]
pub fn read_existing_inputs_hash(path: &Path) -> Option<String> {
    let content = std::fs::read_to_string(path).ok()?;
    let value: serde_json::Value = serde_json::from_str(&content).ok()?;
    value.get("inputsHash")?.as_str().map(String::from)
}

/// Recursively collect all Cargo.toml files under a directory.
///
/// Skips `target/`, `.git/`, and `node_modules/` to avoid noise from
/// build artifacts, vendored dependencies, and non-Rust tooling.
fn collect_cargo_tomls(dir: &Path, out: &mut Vec<PathBuf>) {
    let cargo_toml = dir.join("Cargo.toml");
    if cargo_toml.is_file() {
        out.push(cargo_toml);
    }

    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };

    for entry in entries.flatten() {
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if !file_type.is_dir() {
            continue;
        }
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if SKIP_DIRS.iter().any(|s| *s == &*name_str) {
            continue;
        }
        collect_cargo_tomls(&entry.path(), out);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn make_cli() -> Cli {
        Cli {
            manifest_path: PathBuf::from("./Cargo.toml"),
            features: None,
            bin: None,
            package: None,
            all_features: false,
            no_default_features: false,
            target: None,
            output: PathBuf::from("build-plan.json"),
            stdout: false,
            check_overrides: false,
            include_dev: false,
            members: None,
            no_check: false,
            json: false,
            force: false,
            workspace: false,
            no_locked: false,
            build_std: None,
            build_std_features: None,
        }
    }

    #[test]
    fn fingerprint_is_deterministic() {
        let cli = make_cli();
        let h1 = compute_inputs_hash(&cli).unwrap();
        let h2 = compute_inputs_hash(&cli).unwrap();
        assert_eq!(h1, h2);
    }

    #[test]
    fn fingerprint_is_sha256_hex() {
        let cli = make_cli();
        let hash = compute_inputs_hash(&cli).unwrap();
        assert_eq!(hash.len(), 64);
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn fingerprint_changes_with_features() {
        let cli1 = make_cli();
        let mut cli2 = make_cli();
        cli2.features = Some("serde".to_string());

        let h1 = compute_inputs_hash(&cli1).unwrap();
        let h2 = compute_inputs_hash(&cli2).unwrap();
        assert_ne!(h1, h2, "different features should produce different hashes");
    }

    #[test]
    fn fingerprint_changes_with_target() {
        let cli1 = make_cli();
        let mut cli2 = make_cli();
        cli2.target = Some("aarch64-unknown-linux-gnu".to_string());

        let h1 = compute_inputs_hash(&cli1).unwrap();
        let h2 = compute_inputs_hash(&cli2).unwrap();
        assert_ne!(h1, h2, "different targets should produce different hashes");
    }

    #[test]
    fn fingerprint_changes_with_include_dev() {
        let cli1 = make_cli();
        let mut cli2 = make_cli();
        cli2.include_dev = true;

        let h1 = compute_inputs_hash(&cli1).unwrap();
        let h2 = compute_inputs_hash(&cli2).unwrap();
        assert_ne!(h1, h2, "include_dev should change the hash");
    }

    #[test]
    fn fingerprint_changes_with_workspace() {
        let cli1 = make_cli();
        let mut cli2 = make_cli();
        cli2.workspace = true;

        let h1 = compute_inputs_hash(&cli1).unwrap();
        let h2 = compute_inputs_hash(&cli2).unwrap();
        assert_ne!(h1, h2, "workspace should change the hash");
    }

    #[test]
    fn read_existing_hash_missing_file() {
        assert_eq!(read_existing_inputs_hash(Path::new("/nonexistent")), None);
    }

    #[test]
    fn read_existing_hash_no_field() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("plan.json");
        std::fs::write(&path, r#"{"version": 1, "crates": {}}"#).unwrap();
        assert_eq!(read_existing_inputs_hash(&path), None);
    }

    #[test]
    fn read_existing_hash_present() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("plan.json");
        std::fs::write(
            &path,
            r#"{"version": 1, "inputsHash": "abc123def456"}"#,
        )
        .unwrap();
        assert_eq!(
            read_existing_inputs_hash(&path),
            Some("abc123def456".to_string())
        );
    }

    #[test]
    fn collect_cargo_tomls_finds_root() {
        let mut paths = Vec::new();
        collect_cargo_tomls(Path::new("."), &mut paths);
        assert!(
            paths.iter().any(|p| p.ends_with("Cargo.toml")),
            "should find at least the root Cargo.toml"
        );
    }

    #[test]
    fn collect_cargo_tomls_skips_target() {
        let mut paths = Vec::new();
        collect_cargo_tomls(Path::new("."), &mut paths);
        assert!(
            !paths.iter().any(|p| p
                .components()
                .any(|c| c.as_os_str() == "target")),
            "should not descend into target/"
        );
    }
}
